rp.endpoint =https://rp.epam.com

rp.api.key = module13_aMYzLwvbR22Nsz06VhSj3AJZe0whr9UDmlsJoSkAFVKOr4YykZS4rDfHfxlbd7Sk

rp.project = saba_beridze_personal

rp.enable = true

rp.launch=QA Training Automation

rp.reporting.async=true

rp.reporting.callback=true